version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  db_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data: